Numpy - Numerical Python
 

A general-purpose array processing package is called Numpy. It offers tools for manipulating these arrays as well as a high-performance multidimensional array object. This is the core Python module for scientific computing.

Import Numpy

In [1]:
import numpy as np
np.__version__

'2.0.1'

To Make Array using Numpy module

In [2]:
arr = np.array([25,10,40,50,60])
arr

array([25, 10, 40, 50, 60])

To find the type of Datatypes

In [3]:
type(arr)

numpy.ndarray

In [4]:
ls = [25,10,40,50,60]
arr = np.array(ls)
arr

array([25, 10, 40, 50, 60])

In [5]:
type(ls)

list

Find the Dimension of the Array

In [6]:
arr.ndim

1

Find the size of the Array

In [7]:
arr.size

5

Find the length/Size of Array using len() function

In [8]:
len(arr)

5

Shape of the Array

In [9]:
arr.shape

(5,)

To find the datatypes of Array

In [10]:
arr.dtype

dtype('int64')

In this Array We are using Referential data

In [11]:
arr = np.array([25,10,20,30,40,50,60,"hello"])
arr

array(['25', '10', '20', '30', '40', '50', '60', 'hello'], dtype='<U21')

Indexing in Numpy Modules

In [12]:
arr = np.array([10,20,30,40,50,60,70,80,90])
arr
arr[-3:]
arr[-1:-4:-5]
arr[1:-4:5]
arr[-3:7]

array([70])

If we perform addition operation, then each elements of the Array is increment by 5

In [13]:
arr + 5

array([15, 25, 35, 45, 55, 65, 75, 85, 95])

If we perform Subtraction operation, then each elements of the Array is decrement by 5

In [14]:
arr -5

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85])

If we perform Multiplication operation, then each elements of the Array is multiply by 5

In [15]:
arr *5

array([ 50, 100, 150, 200, 250, 300, 350, 400, 450])

In [16]:
arr /2

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45.])

To Find the Maximum value in Array

In [17]:
max(arr)

np.int64(90)

To Add all the value of the Array

In [18]:
sum(arr)

np.int64(450)

Mean = Average 

In [19]:
np.mean(arr)
# The Datatype of the Mean is Float

np.float64(50.0)

Middle Most Element in the Array

In [20]:
np.median(arr)

np.float64(50.0)

In [21]:
np.mode(arr)

AttributeError: module 'numpy' has no attribute 'mode'

Importing Random to Generate random integer value

In [25]:
import random

In [26]:
random.randint(1,9)    #0 to 9

8

This Function is Used to Generate 500 integer value which are all between 1 to 450

In [27]:
arr = np.random.randint(1,450,500)    # create 500 random number from 1 to 450
arr

array([360,  39, 383, 145, 145, 318, 444,  31, 166, 265, 123, 432, 294,
       177, 183, 146, 313, 307, 318, 267, 204, 383,   9, 131,  87, 219,
       413, 106, 106, 245, 207, 349, 285, 313, 109, 410, 376, 103, 230,
       360,  51, 228, 308, 408, 231, 174, 392, 353, 441, 294,  29, 240,
         9, 315, 316,  66, 375, 319,  91, 426, 122, 230,  74,  10, 270,
       100, 369, 225, 251,  60, 139, 303, 187,  49, 439, 279, 324, 125,
       378, 322, 432, 340,  64,  82,  50, 422, 323, 448, 382,  69, 203,
       377, 355, 371,  20, 172,  70, 386, 287,   8, 341,  36, 300, 173,
       272,  26, 358, 344, 318, 431,  47, 187, 245, 159,  96, 208, 281,
       381, 345, 255, 191, 436,  40, 312, 367, 120, 188, 301, 370, 346,
       201, 322, 307, 396,  45, 123, 356, 104, 268, 413,  81, 166, 304,
       252, 250, 388, 432, 228, 365, 361, 174, 201, 331, 399, 281, 427,
        51, 165, 276,  41,  92, 131, 150, 437, 363, 171, 301, 447, 346,
       417, 195, 150, 264, 315, 308, 325, 254, 186, 394, 330, 25

In [28]:
arr = np.random.randint(1,450,500)    # create 500 random number from 1 to 450
arr

# try to calculate no of item that are less than 100
# try to calculate no of even count

array([268, 362,  84, 225, 135,  14, 313, 266, 347, 187, 178, 107, 281,
        35, 323, 125,  23, 304,  90, 279, 227,  37, 245, 119, 291, 122,
       324, 114, 437, 347, 220, 190, 352, 449,   9, 440, 193, 274, 371,
       396, 224,  18,  84, 311, 323, 418, 337, 319, 398, 335, 100, 430,
       387, 398, 302, 351,  19, 299, 320, 275, 408,  48, 202, 187, 163,
       228, 112, 346, 324, 111, 300, 386, 220, 367, 176, 435, 302, 186,
       174, 251, 388, 288, 109,  31, 112,  59, 120, 254,   6,  88, 125,
        24, 113, 313, 240, 257, 404, 382, 171, 192, 109,  56, 324, 265,
       259, 341, 289, 295, 339, 196, 272, 433, 332,  47, 153,  56, 115,
       207, 142, 156, 114,  98, 270, 322,  16, 334,  88, 288, 322, 418,
        26, 186, 117,  61, 233,  98, 137, 364,  37,  93, 191,  70, 186,
       267, 320, 425, 208, 114, 324, 229,  85, 218, 190, 204,  95, 433,
       433, 268, 326, 186, 349, 234, 218, 428, 390, 203, 434,  38, 114,
       365, 291, 140, 370, 163, 414, 440, 105, 401, 289, 402, 11

Calculate the no. of items that are greater than 100

In [29]:
count_greater_than_100 = np.sum(arr > 100)

print(f'Number of values greater than 100: {count_greater_than_100}')

Number of values greater than 100: 398


Calculate the no. of items that are less than 100

In [30]:
count_less_than_100 = np.sum(arr < 100)

print(f'Number of values less than 100: {count_less_than_100}')

Number of values less than 100: 97


In [31]:
count_even = np.sum(arr % 2 == 0)

print(f'Number of even values: {count_even}')

Number of even values: 256


In [32]:
count_odd = arr[arr % 2 != 0]
for no in count_odd :
    print(no)

225
135
313
347
187
107
281
35
323
125
23
279
227
37
245
119
291
437
347
449
9
193
371
311
323
337
319
335
387
351
19
299
275
187
163
111
367
435
251
109
31
59
125
113
313
257
171
109
265
259
341
289
295
339
433
47
153
115
207
117
61
233
137
37
93
191
267
425
229
85
95
433
433
349
203
365
291
163
105
401
289
349
197
327
61
11
121
143
363
245
165
375
227
273
15
11
171
293
347
205
315
209
325
423
437
127
69
417
51
299
421
203
431
267
341
379
299
183
89
345
317
39
155
299
441
279
325
65
331
125
411
113
279
13
129
227
411
355
427
5
353
153
151
219
297
129
347
261
429
145
177
371
219
171
11
361
281
31
89
249
367
235
243
175
313
113
391
209
267
63
267
111
433
401
343
283
227
369
399
35
317
359
341
1
375
441
399
171
17
277
233
131
239
113
339
169
53
329
403
405
115
199
177
83
235
385
21
83
293
429
49
415
417
75
11
133
327
185
225
333
219
265
247
3
5
209
83
243
107
157
29
337
133
269
311
17
433
399
169
181
277
437
363
383


2D Array in Numpy

In [33]:
ls =[[1,2,3],
    [4,5,6],
    [7,8,9]]
ls
type(ls)

list

In [34]:
arr2 = np.array(ls)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

To Find Dimension of Array

In [35]:
arr2.ndim

2

Shape of the Array

In [36]:
arr2.shape

(3, 3)

Indexing Of the Array

In [37]:
arr2[1]

array([4, 5, 6])

In [38]:
arr2[0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr2[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [40]:
arr2[0:2,1]

array([2, 5])

In [41]:
arr2[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [42]:
arr2[-2]

array([4, 5, 6])

In [43]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr2[0:,2]

array([3, 6, 9])

Functions of Numpy For 2D Array

In [45]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
np.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

3 Dimensional Array

In [48]:
# 3d array
import numpy as np

In [49]:
ls = [[[1, 2, 3], [4, 5, 6],
       [7, 8, 9]], [[1, 2, 3],
        [4, 5, 6], [7, 8, 9]],
      [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
      [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]
ls

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [50]:
arr3= np.array(ls)
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [51]:
arr3.shape

(4, 3, 3)

In [52]:
arr3.ndim

3

In [53]:
arr3[1]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr3[0:,2:1,2:1]

array([], shape=(4, 0, 0), dtype=int64)

In [55]:
arr3[-4:,-2:,-2:]

array([[[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]]])

In [56]:
arr3[-3:,-3:,1]

array([[2, 5, 8],
       [2, 5, 8],
       [2, 5, 8]])

In [57]:
arr3[2,1:,1:]

array([[5, 6],
       [8, 9]])

In [58]:
arr3.ravel()  # is used to convert 3 d array in 1d array

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr3.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr3.reshape(36)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

argmin() Function

In [62]:
import numpy as np
arr = np.array([10, 3, 5, 2, 8, 7])
min_index = np.argmin(arr)
print("The index of the minimum value is:", min_index)

The index of the minimum value is: 3


argmax() Function

In [65]:
import numpy as np
arr = np.array([10, 3, 5, 12, 8, 7])
max_index = np.argmax(arr)
print("The index of the maximum value is:", max_index)

The index of the maximum value is: 3


argsort() Function

In [66]:
import numpy as np
arr = np.array([10, 3, 5, 12, 8, 7])
sorted_indices = np.argsort(arr)
print("The indices that would sort the array are:", sorted_indices)

The indices that would sort the array are: [1 2 5 4 0 3]
